apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-demo-app-argo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mmurth/openshift-demo/
    targetRevision: HEAD
    path: argocd/dev
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
